# Generated by Django 2.2.12 on 2022-08-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20220720_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Repoter',
        ),
    ]
